# Generated by Django 2.2.2 on 2019-06-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_port'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='port',
            new_name='Portfolio',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pub_date',
            new_name='image',
        ),
    ]
